version: "3.8"

services:
  spring:
    build: app/.
    container_name: cve-2021-44228
    image: ahmad4fifz/cve-2021-44228
    environment:
      - TZ="Asia/Kuala_Lumpur"
    networks:
      - cve-2021-44228
    ports:
      - "8080"
    restart: always
    volumes:
      - ./data:/app

  proxy:
    build: proxy/.
    container_name: reverse_proxy
    image: ahmad4fifz/reverse_proxy
    environment:
      - TZ="Asia/Kuala_Lumpur"
    networks:
      - cve-2021-44228
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./data:/var/log
      - caddy_data:/data
      - caddy_config:/config

networks:
  cve-2021-44228:
    name: cve-2021-44228

volumes:
  caddy_data:
  caddy_config: